
project_id = "haxiwqgajhanpapvicbm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

# JWT verification is enabled for this function
[functions.analyze-meal-photo]
verify_jwt = true

# JWT verification is enabled for this function
[functions.voice-workout-parser]
verify_jwt = true

[functions.analyze-fitness-assessment]
enabled = true
verify_jwt = true
import_map = "./functions/analyze-fitness-assessment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/analyze-fitness-assessment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/analyze-fitness-assessment/*.html" ]

# AI Chat function configuration
[functions.ai-chat]
enabled = true
verify_jwt = true
